### ISSUE TITLE
question: is valuable expected to work with tracing macros?

### ISSUE THREAD

**Issue by OliverNChalk** [tokio-rs/valuable#115]
I was expecting valuable to work out of the box with tracing's macros (`info`, `debug` etc). However, I get an issue saying `Value` is not implemented for my type (i.e. there is no blanket implementation covering all types that implement Valuable). This currently seems like the only way to make tracing happy:

```rust
for (service, old_state) in removed {
    info!(service = &service as &dyn Valuable,"Service unit removed");
    self.service_state.remove(&service);
}
```

Please let me know if this was an oversight, or if there's a fundamental limitation preventing the compiler from auto-coercing my type (`RemoteServiceId`) that implements Valuable to Value?

**Comment by fluffysquirrels** [comment]
First you need to enable the `tracing_unstable` rustc flag and the `valuable` feature in the `tracing` crate. [Ref](https://docs.rs/tracing/latest/tracing/#unstable-features).

Then you need to call `.as_value()` on the value before using a tracing macro, e.g.:

```rust
tracing::info!(service = service.as_value(), "Service unit removed");
```
