### ISSUE TITLE
Release initial version

### ISSUE THREAD

**Issue by xd009642** [tokio-rs/valuable#66]
So valuable integration has started in tracing ( https://github.com/tokio-rs/tracing/pull/1608 ) but a blocker for merging it is that valuable needs a release on crates.io. I'm aware there's a milestone for features for the 0.1 release so if that's not ready potentially an alpha release? Or depending on the milestone features punt them to a patch or the next version

**Comment by carllerche** [comment]
Looks like @hawkw owns the crate name. I requested permission.

**Comment by xd009642** [comment]
@taiki-e @carllerche how many of the milestone issues must go in before the initial release? Or are there some that the team would be comfortable punting to the next release? Just out of curiosity as I'd like to help clear any of the blockers if possible

**Comment by taiki-e** [comment]
https://crates.io/crates/valuable/0.1.0
